#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : confuse
Version  : 3.2.2
Release  : 6
URL      : https://github.com/martinh/libconfuse/releases/download/v3.2.2/confuse-3.2.2.tar.gz
Source0  : https://github.com/martinh/libconfuse/releases/download/v3.2.2/confuse-3.2.2.tar.gz
Summary  : configuration file parser library
Group    : Development/Tools
License  : ISC
Requires: confuse-lib = %{version}-%{release}
Requires: confuse-license = %{version}-%{release}
Requires: confuse-locales = %{version}-%{release}
BuildRequires : flex

%description
libConfuse is a configuration file parser library written in C.
It supports sections and (lists of) values (strings, integers,
floats, booleans or other sections), as well as some other features
(such as single/double-quoted strings, environment variable expansion,
functions and nested include statements).

It makes it easy to add configuration file capability to a
program using a simple API. LibConfuse aims to be easy to use and
quick to integrate with your code.

%package dev
Summary: dev components for the confuse package.
Group: Development
Requires: confuse-lib = %{version}-%{release}
Provides: confuse-devel = %{version}-%{release}
Requires: confuse = %{version}-%{release}

%description dev
dev components for the confuse package.


%package doc
Summary: doc components for the confuse package.
Group: Documentation

%description doc
doc components for the confuse package.


%package lib
Summary: lib components for the confuse package.
Group: Libraries
Requires: confuse-license = %{version}-%{release}

%description lib
lib components for the confuse package.


%package license
Summary: license components for the confuse package.
Group: Default

%description license
license components for the confuse package.


%package locales
Summary: locales components for the confuse package.
Group: Default

%description locales
locales components for the confuse package.


%prep
%setup -q -n confuse-3.2.2
cd %{_builddir}/confuse-3.2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1585184409
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1585184409
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/confuse
cp %{_builddir}/confuse-3.2.2/LICENSE %{buildroot}/usr/share/package-licenses/confuse/511dc3d6a4303ecf5e37b6aa8a452bad7150c5e5
%make_install
%find_lang confuse

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/confuse.h
/usr/lib64/libconfuse.so
/usr/lib64/pkgconfig/libconfuse.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/confuse/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libconfuse.so.2
/usr/lib64/libconfuse.so.2.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/confuse/511dc3d6a4303ecf5e37b6aa8a452bad7150c5e5

%files locales -f confuse.lang
%defattr(-,root,root,-)

