#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : confuse
Version  : 3.2.1
Release  : 2
URL      : https://github.com/martinh/libconfuse/releases/download/v3.2.1/confuse-3.2.1.tar.xz
Source0  : https://github.com/martinh/libconfuse/releases/download/v3.2.1/confuse-3.2.1.tar.xz
Summary  : configuration file parser library
Group    : Development/Tools
License  : ISC
Requires: confuse-lib
Requires: confuse-doc
Requires: confuse-locales
BuildRequires : flex

%description
libConfuse is a configuration file parser library written in C.
It supports sections and (lists of) values (strings, integers,
floats, booleans or other sections), as well as some other features
(such as single/double-quoted strings, environment variable expansion,
functions and nested include statements).

It makes it easy to add configuration file capability to a
program using a simple API. LibConfuse aims to be easy to use and
quick to integrate with your code.

%package dev
Summary: dev components for the confuse package.
Group: Development
Requires: confuse-lib
Provides: confuse-devel

%description dev
dev components for the confuse package.


%package doc
Summary: doc components for the confuse package.
Group: Documentation

%description doc
doc components for the confuse package.


%package lib
Summary: lib components for the confuse package.
Group: Libraries

%description lib
lib components for the confuse package.


%package locales
Summary: locales components for the confuse package.
Group: Default

%description locales
locales components for the confuse package.


%prep
%setup -q -n confuse-3.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1525285620
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1525285620
rm -rf %{buildroot}
%make_install
%find_lang confuse

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libconfuse.so
/usr/lib64/pkgconfig/libconfuse.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/confuse/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libconfuse.so.2
/usr/lib64/libconfuse.so.2.0.0

%files locales -f confuse.lang
%defattr(-,root,root,-)

